### ISSUE TITLE
Mismatching between the master branch and the npm package

### ISSUE THREAD

**Issue by fbouteruche** [microsoft/Cognitive-LUIS-Node.js#8]
Hi guy,

The npm package here https://www.npmjs.com/package/luis-sdk matches the development branch and not the master branch.

Can you fix this please ?

Thanks,
François.

**Comment by zcmack** [comment]
just to reiterate this point -- the npm package is out of date and does not work with the following error:

`{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }`

once i replaced the npm package with the sdk code from this library it is working as expected. seems the npm repo just needs updating.

**Comment by ritikrishu** [comment]
any update on this?
